### ISSUE TITLE
How to set background color on week number & day header?

### ISSUE THREAD

**Issue by limelime** [dmedvinsky/gsimplecal#28]
How to set background color on week number & day header like in your screenshot(it is blue).
Mine is white.

**Comment by dmedvinsky** [comment]
Sorry, currently in the hospital with no computer so I can't give you any
details, but the short answer is that it solely depends on your GTK theme.
Gsimplecal itself doesn't set any colors, so you need to research the GTK
themes subject.


On Jan 20, 2017 22:52, "limelime" <notifications@github.com> wrote:

How to set background color on week number & day header like in your
screenshot(it is blue).
Mine is white.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmedvinsky/gsimplecal/issues/28>, or mute the thread

**Comment by limelime** [comment]
Solution: Change /root/.config/gtk-3.0/gtk.css
```css
/* Calendar week, day label */
GtkCalendar.highlight 
{
	background-color: #398ee7;
	color: white;
	font-weight: bold;
}

/*Calendar content*/
GtkCalendar.view
{
	background-color: $selected_bg_color;
	text-align: right;
}

/* day selected */
GtkCalendar:selected
{
	background-color: $selected_bg_color;
}


/* Month and year */
GtkCalendar.header
{
	color: $selected_fg_color;
}
```
